version: '3.2'
services:
  elasticsearch:
    image: elasticsearch:7.17.1
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch
    environment:
      # 单节点
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - TAKE_FILE_OWNERSHIP=true
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
  kibana:
    image: kibana:7.17.1
    ports:
      - 5601:5601
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml